import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Title from "@/components/LandingPage/Title";
import Subtitle from "@/components/LandingPage/Subtitle";
import MoreInfo from "@/components/LandingPage/MoreInfo";
import IllustrationAlpha from "@/components/LandingPage/IllustrationAlpha";
import { animate, motion } from "framer-motion";
import Button from "@/components/LandingPage/Button";
import MiniProfile from "@/components/LandingPage/MiniProfile";
import LandingPage from "@/components/LandingPage/LandingPage";
import { useUser } from "@auth0/nextjs-auth0/client";
import HomePage from "@/components/HomePage/HomePage";
import Loading from "@/components/Loading";

const inter = Inter({ subsets: ["latin"] });

const mainContainerStyles =
  "w-screen h-screen flex flex-col space-y-6 justify-center"

const mainContentStyles = "w-full h-full flex flex-col bg-stone-200 dark:bg-stone-900 justify-center";

export default function Home() {

  const { user, error, isLoading } = useUser();

  if (isLoading) return (<Loading>Loading</Loading>);
  if (error) return <div>{error.message}</div>;

  if(user)
  {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <HomePage user={user}></HomePage>
      </>
    );
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingPage></LandingPage>
    </>
  );
}
